export type SystemTags =
    | 'Render'
    | 'PositionLimit'
    | 'DecorSpawn'
    | 'SpacetimeDBEventSystem'
    | 'MouseInput'
    | 'KeyInput'
    | 'EnergySystem'
    | 'CursorSystem'
    | 'OpenDoorSystem'
    | 'FadeSystem'
    | 'DecorEventSystem'
    | 'InventoryEventSystem'
    | 'PackageEventSystem'
    | 'TweenSystem'
    | 'DialogueController';
