// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.5.0 (commit 0712d3bfbd159367de09efeeeacb54c9d4f0ff61).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { CreateDecor } from "./create_decor_reducer.ts";
export { CreateDecor };
import { DeleteDecor } from "./delete_decor_reducer.ts";
export { DeleteDecor };
import { EnterDoor } from "./enter_door_reducer.ts";
export { EnterDoor };
import { IdentityConnected } from "./identity_connected_reducer.ts";
export { IdentityConnected };
import { LikeDecor } from "./like_decor_reducer.ts";
export { LikeDecor };
import { MoveDecor } from "./move_decor_reducer.ts";
export { MoveDecor };
import { UpdateDecorText } from "./update_decor_text_reducer.ts";
export { UpdateDecorText };

// Import and reexport all table handle types
import { DecorTableHandle } from "./decor_table.ts";
export { DecorTableHandle };
import { DoorTableHandle } from "./door_table.ts";
export { DoorTableHandle };
import { InteractionTableHandle } from "./interaction_table.ts";
export { InteractionTableHandle };
import { UserTableHandle } from "./user_table.ts";
export { UserTableHandle };

// Import and reexport all types
import { Decor } from "./decor_type.ts";
export { Decor };
import { Door } from "./door_type.ts";
export { Door };
import { Interaction } from "./interaction_type.ts";
export { Interaction };
import { User } from "./user_type.ts";
export { User };

const REMOTE_MODULE = {
  tables: {
    decor: {
      tableName: "decor",
      rowType: Decor.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Decor.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    door: {
      tableName: "door",
      rowType: Door.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Door.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    interaction: {
      tableName: "interaction",
      rowType: Interaction.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Interaction.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    user: {
      tableName: "user",
      rowType: User.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: (User.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    create_decor: {
      reducerName: "create_decor",
      argsType: CreateDecor.getTypeScriptAlgebraicType(),
    },
    delete_decor: {
      reducerName: "delete_decor",
      argsType: DeleteDecor.getTypeScriptAlgebraicType(),
    },
    enter_door: {
      reducerName: "enter_door",
      argsType: EnterDoor.getTypeScriptAlgebraicType(),
    },
    identity_connected: {
      reducerName: "identity_connected",
      argsType: IdentityConnected.getTypeScriptAlgebraicType(),
    },
    like_decor: {
      reducerName: "like_decor",
      argsType: LikeDecor.getTypeScriptAlgebraicType(),
    },
    move_decor: {
      reducerName: "move_decor",
      argsType: MoveDecor.getTypeScriptAlgebraicType(),
    },
    update_decor_text: {
      reducerName: "update_decor_text",
      argsType: UpdateDecorText.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.5.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CreateDecor", args: CreateDecor }
| { name: "DeleteDecor", args: DeleteDecor }
| { name: "EnterDoor", args: EnterDoor }
| { name: "IdentityConnected", args: IdentityConnected }
| { name: "LikeDecor", args: LikeDecor }
| { name: "MoveDecor", args: MoveDecor }
| { name: "UpdateDecorText", args: UpdateDecorText }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  createDecor(key: string, x: number, y: number) {
    const __args = { key, x, y };
    let __writer = new __BinaryWriter(1024);
    CreateDecor.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_decor", __argsBuffer, this.setCallReducerFlags.createDecorFlags);
  }

  onCreateDecor(callback: (ctx: ReducerEventContext, key: string, x: number, y: number) => void) {
    this.connection.onReducer("create_decor", callback);
  }

  removeOnCreateDecor(callback: (ctx: ReducerEventContext, key: string, x: number, y: number) => void) {
    this.connection.offReducer("create_decor", callback);
  }

  deleteDecor(decorId: bigint) {
    const __args = { decorId };
    let __writer = new __BinaryWriter(1024);
    DeleteDecor.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("delete_decor", __argsBuffer, this.setCallReducerFlags.deleteDecorFlags);
  }

  onDeleteDecor(callback: (ctx: ReducerEventContext, decorId: bigint) => void) {
    this.connection.onReducer("delete_decor", callback);
  }

  removeOnDeleteDecor(callback: (ctx: ReducerEventContext, decorId: bigint) => void) {
    this.connection.offReducer("delete_decor", callback);
  }

  enterDoor() {
    this.connection.callReducer("enter_door", new Uint8Array(0), this.setCallReducerFlags.enterDoorFlags);
  }

  onEnterDoor(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("enter_door", callback);
  }

  removeOnEnterDoor(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("enter_door", callback);
  }

  onIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_connected", callback);
  }

  removeOnIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_connected", callback);
  }

  likeDecor(decorId: bigint) {
    const __args = { decorId };
    let __writer = new __BinaryWriter(1024);
    LikeDecor.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("like_decor", __argsBuffer, this.setCallReducerFlags.likeDecorFlags);
  }

  onLikeDecor(callback: (ctx: ReducerEventContext, decorId: bigint) => void) {
    this.connection.onReducer("like_decor", callback);
  }

  removeOnLikeDecor(callback: (ctx: ReducerEventContext, decorId: bigint) => void) {
    this.connection.offReducer("like_decor", callback);
  }

  moveDecor(decorId: bigint, x: number, y: number, rot: number) {
    const __args = { decorId, x, y, rot };
    let __writer = new __BinaryWriter(1024);
    MoveDecor.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("move_decor", __argsBuffer, this.setCallReducerFlags.moveDecorFlags);
  }

  onMoveDecor(callback: (ctx: ReducerEventContext, decorId: bigint, x: number, y: number, rot: number) => void) {
    this.connection.onReducer("move_decor", callback);
  }

  removeOnMoveDecor(callback: (ctx: ReducerEventContext, decorId: bigint, x: number, y: number, rot: number) => void) {
    this.connection.offReducer("move_decor", callback);
  }

  updateDecorText(decorId: bigint, text: string) {
    const __args = { decorId, text };
    let __writer = new __BinaryWriter(1024);
    UpdateDecorText.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_decor_text", __argsBuffer, this.setCallReducerFlags.updateDecorTextFlags);
  }

  onUpdateDecorText(callback: (ctx: ReducerEventContext, decorId: bigint, text: string) => void) {
    this.connection.onReducer("update_decor_text", callback);
  }

  removeOnUpdateDecorText(callback: (ctx: ReducerEventContext, decorId: bigint, text: string) => void) {
    this.connection.offReducer("update_decor_text", callback);
  }

}

export class SetReducerFlags {
  createDecorFlags: __CallReducerFlags = 'FullUpdate';
  createDecor(flags: __CallReducerFlags) {
    this.createDecorFlags = flags;
  }

  deleteDecorFlags: __CallReducerFlags = 'FullUpdate';
  deleteDecor(flags: __CallReducerFlags) {
    this.deleteDecorFlags = flags;
  }

  enterDoorFlags: __CallReducerFlags = 'FullUpdate';
  enterDoor(flags: __CallReducerFlags) {
    this.enterDoorFlags = flags;
  }

  likeDecorFlags: __CallReducerFlags = 'FullUpdate';
  likeDecor(flags: __CallReducerFlags) {
    this.likeDecorFlags = flags;
  }

  moveDecorFlags: __CallReducerFlags = 'FullUpdate';
  moveDecor(flags: __CallReducerFlags) {
    this.moveDecorFlags = flags;
  }

  updateDecorTextFlags: __CallReducerFlags = 'FullUpdate';
  updateDecorText(flags: __CallReducerFlags) {
    this.updateDecorTextFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get decor(): DecorTableHandle {
    // clientCache is a private property
    return new DecorTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Decor>(REMOTE_MODULE.tables.decor));
  }

  get door(): DoorTableHandle {
    // clientCache is a private property
    return new DoorTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Door>(REMOTE_MODULE.tables.door));
  }

  get interaction(): InteractionTableHandle {
    // clientCache is a private property
    return new InteractionTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Interaction>(REMOTE_MODULE.tables.interaction));
  }

  get user(): UserTableHandle {
    // clientCache is a private property
    return new UserTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<User>(REMOTE_MODULE.tables.user));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
